### PR TITLE
merged routing classification and science area into one column and removed drop down

### PR DESCRIPTION
**Pull request by ellesmith88**

### CODE REVIEW

**Comment by rsmith013** [comment]
I wonder whether we should put all labels in, rather than just the top one?

**Comment by ellesmith88** [comment]
Quite possibly, wasn't 100% happy with so haven't pushed it. Might be worth asking Kate.

**Comment by rsmith013** [comment]
Yea, I wonder whether it should just be labels and list all of them. Perhaps in order for the science areas. We could have the percentages displayed in the table and then filter them out for the facet.

We can ask Kate

**Comment by ellesmith88** [comment]
closes #162

**Pull request merged**
