### PR TITLE
Issue/265/admins see users

### LINKED ISSUE #265: Add way for admins to see other users linked to their datacentre

### PR DESCRIPTION
**Pull request by ellesmith88**
Added list of users - with options to edit/remove users

closes #265

### CODE REVIEW

**Comment by rsmith013** [comment]
I have made a couple of changes:
- Moved the add user button to remove clutter from the menu
- Made user of the fields attribute of table to have a smaller list to maintain
- Added a boolean field template to use font awesome styling
- Centred the text in the columns, except the actions
- Dropped the filter to remove the current user, make sense to see everyone. We would get questions, "where am I in this list?"

**Review by rsmith013 — APPROVED** [review]

**Comment by ellesmith88** [comment]
@rsmith013 The javascript was to pop up a message to confirm whether they want to remove the user or not. I think it would make sense to have that in

**Comment by rsmith013** [comment]
@ellesmith88 You are right, apologies.

**Comment by rsmith013** [comment]
Removed last commit

**Pull request merged**
